## INTEGRANTES

# Sannyer Cardoso Carvalho Nery
# Fani Tamires de Souza Batista
# Carlos Eduardo Araujo
# Wallace Almeida dos Santos

In [26]:
pip install pymysql

Collecting pymysql
  Using cached PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Using cached PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
Note: you may need to restart the kernel to use updated packages.

In [144]:
def verifica(lista, lista2):
    # Converta todos os itens da lista para maiúsculas
    lista = [item.upper() for item in lista]
    
    for item in lista2:
        # Converta o item atual para maiúsculas
        if item.upper() in lista:
            print("Já existe a tabela:", item)
        else:
            print("Não existe a tabela:", item)

In [155]:
def filtraTabelasExistentes(lista, lista2):
    # Converta todos os itens da lista para maiúsculas
    lista = [item.upper() for item in lista]
    list_filtrada = []
    for item in lista2:
        # Converta o item atual para maiúsculas
        if item.upper() in lista:
            print("Já existe a tabela:", item)
        else:
            lista_filtrada.append(item)
            print("Não existe a tabela:", item)
    return lista_filtrada

In [1]:
def verificar_relacionamentos(schema_name, tabela_selecionada):
    conn_oraclecatalog = conecta_mysql_oraclecatalog()
    cursor_catalog = conn_oraclecatalog.cursor()
    
    cursor_catalog.execute(f"CALL sp_relacionamento('{schema_name}', '{tabela_selecionada}');")
    relacionamentos = cursor_catalog.fetchall()

    if relacionamentos:
        print(f"Tabela {tabela_selecionada} possui relacionamentos:")
        for relacionamento in relacionamentos:
            print(relacionamento)
    else:
        print(f"Tabela {tabela_selecionada} não possui relacionamentos.")

    conn_oraclecatalog.close()

In [150]:
import tkinter as tk
from tkinter import messagebox, ttk
import mysql.connector
import cx_Oracle
from tkinter import Menu
import pymysql

db_config = {}
db_configorcl = {}

def janela_config_bd02(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura):
    janela05 = tk.Toplevel()
    janela05.title("Configuração do Banco de Dados Oracle")
    janela05.geometry("900x450")

    # Criação dos campos de entrada para conexão ao BD Oracle
    tk.Label(janela05, text="Usuário:").grid(row=0, column=0, padx=10, pady=10)
    username_entry = tk.Entry(janela05, width=20)
    username_entry.grid(row=0, column=1, padx=10, pady=10)

    tk.Label(janela05, text="Senha:").grid(row=1, column=0, padx=10, pady=10)
    password_entry = tk.Entry(janela05, width=20, show="*")
    password_entry.grid(row=1, column=1, padx=10, pady=10)

    tk.Label(janela05, text="Host:").grid(row=2, column=0, padx=10, pady=10)
    host_entry = tk.Entry(janela05, width=20)
    host_entry.grid(row=2, column=1, padx=10, pady=10)

    tk.Label(janela05, text="Porta:").grid(row=3, column=0, padx=10, pady=10)
    port_entry = tk.Entry(janela05, width=20)
    port_entry.grid(row=3, column=1, padx=10, pady=10)

    tk.Label(janela05, text="Nome do Serviço:").grid(row=4, column=0, padx=10, pady=10)
    service_name_entry = tk.Entry(janela05, width=20)
    service_name_entry.grid(row=4, column=1, padx=10, pady=10)

    def salva_config():
        db_configorcl["user"] = username_entry.get()
        db_configorcl["password"] = password_entry.get()
        db_configorcl["host"] = host_entry.get()
        db_configorcl["port"] = port_entry.get()
        db_configorcl["service_name"] = service_name_entry.get()

        janela05.destroy()
        verifica_relacionamento(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura)

    conect_button = tk.Button(master=janela05, text="CONECTAR", command=salva_config)
    conect_button.grid(row=5, column=0, columnspan=2, padx=10, pady=10)

    voltar_button = tk.Button(janela05, text="VOLTAR", command=janela05.destroy)
    voltar_button.grid(row=5, column=2, columnspan=2, padx=10, pady=10)
    
def verifica_relacionamento(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura):
    mysql_conn = pymysql.connect(
        user=db_config["user"],
        password=db_config["password"],
        host=db_config["host"],
        database=banco_selecionado
    )
    cursor = mysql_conn.cursor()
    cursor.callproc("sp_tabela_necessaria", (banco_selecionado, tabela_selecionada))
    resultados = cursor.fetchall()
    if resultados:
        for result in resultados:

            migrar_banco(banco_selecionado, result[0], migrar_estrutura_dados, migrar_somente_estrutura)
        migrar_banco(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura)
    else:
        migrar_banco(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura)
            
    
def migrar_banco(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura):
    mysql_conn = None
    try:
        dsn = cx_Oracle.makedsn(db_configorcl["host"], db_configorcl["port"], service_name=db_configorcl["service_name"])
        conn = cx_Oracle.connect(user=db_configorcl["user"], password=db_configorcl["password"], dsn=dsn)

        print("Conexão com o banco de dados Oracle bem-sucedida!")

        mysql_conn = mysql.connector.connect(
            user=db_config["user"],
            password=db_config["password"],
            host=db_config["host"],
            database=banco_selecionado
        )
        
        mysql_cursor = mysql_conn.cursor()
        mysql_cursor.execute(f"DESCRIBE {tabela_selecionada};")
        columns = mysql_cursor.fetchall()

        cursor_oracle = conn.cursor()

        # Verificar e migrar chaves primárias
        mysql_cursor.execute(f"SHOW KEYS FROM {tabela_selecionada} WHERE Key_name = 'PRIMARY';")
        primary_keys = mysql_cursor.fetchall()

        create_table_sql = f'CREATE TABLE "{tabela_selecionada.upper()}" ('
        pk_columns = []

        for column in columns:
            column_name = column[0]
            column_type = column[1]

            # Mapeamento de tipos de dados
            if "int" in column_type.lower():
                oracle_type = "NUMBER"
            elif "varchar" in column_type.lower():
                length = column_type.split('(')[1].split(')')[0]
                oracle_type = f"VARCHAR2({length})"
            elif "text" in column_type.lower():
                oracle_type = "CLOB"
            elif "datetime" in column_type.lower():
                oracle_type = "DATE"
            else:
                oracle_type = "VARCHAR2(255)"  # Tipo padrão

            create_table_sql += f'"{column_name.upper()}" {oracle_type}, '

            # Verificar se a coluna é uma chave primária
            for pk in primary_keys:
                if pk[4] == column_name:
                    pk_columns.append(column_name)

        if pk_columns:
            pk_columns_str = ", ".join([f'"{col.upper()}"' for col in pk_columns])
            create_table_sql += f'PRIMARY KEY ({pk_columns_str}), '

        # Remover vírgula extra ao final da instrução SQL
        create_table_sql = create_table_sql.rstrip(", ") + ")"
        
        print(f"Executing: {create_table_sql}")
        cursor_oracle.execute(create_table_sql)

        if migrar_estrutura_dados:
            mysql_cursor.execute(f"SELECT * FROM {tabela_selecionada};")
            rows = mysql_cursor.fetchall()
            for row in rows:
                placeholders = ", ".join([":" + str(i + 1) for i in range(len(row))])
                insert_sql = f"INSERT INTO \"{tabela_selecionada.upper()}\" VALUES ({placeholders})"
                cursor_oracle.execute(insert_sql, row)

        conn.commit()

        print("Migração do banco de dados concluída com sucesso!")

    except cx_Oracle.Error as error:
        messagebox.showerror("Erro de Migração", f"Erro ao migrar o banco de dados: {error}")

    finally:
        if mysql_conn is not None:
            mysql_conn.close()
        conn.close()


def janela_tabela(banco_selecionado):
    janela4 = tk.Toplevel()
    janela4.title("CFSW MIGRAÇÃO DE DADOS")
    janela4.geometry("900x450")  
    janela4.resizable(False, False)

    try:
        cnx = mysql.connector.connect(
            user=db_config["user"],
            password=db_config["password"],
            host=db_config["host"],
            database=banco_selecionado
        )
        cursor = cnx.cursor()
        cursor.execute("SHOW TABLES;")
        rows = cursor.fetchall()
        table_options = [row[0] for row in rows]

    except mysql.connector.Error as err:
        print(f"Erro: {err}")
        return

    tabelas_combobox = ttk.Combobox(janela4, font=("Helvetica", 12))
    tabelas_combobox['values'] = table_options
    tabelas_combobox.current(0)
    tabelas_combobox.grid(row=3, column=0, padx=10, pady=10)

    banco_label = tk.Label(janela4, text="BANCO SELECIONADO", font=("Helvetica", 12))
    banco_label.grid(row=0, column=0, padx=10, pady=10)

    banco_nome = tk.Label(janela4, text=banco_selecionado, font=("Helvetica", 12)) 
    banco_nome.grid(row=1, column=0, padx=10, pady=10)

    estrutura_dados_var = tk.BooleanVar(value=False)
    estrutura_dados_checkbox = tk.Checkbutton(janela4, text="MIGRAR ESTRUTURA E DADOS", variable=estrutura_dados_var, font=("Helvetica", 12))
    estrutura_dados_checkbox.grid(row=4, column=0, padx=10, pady=10)

    somente_estrutura_var = tk.BooleanVar(value=False)
    somente_estrutura_checkbox = tk.Checkbutton(janela4, text="MIGRAR SOMENTE ESTRUTURA", variable=somente_estrutura_var, font=("Helvetica", 12))
    somente_estrutura_checkbox.grid(row=5, column=0, padx=10, pady=10)

    sim_button = tk.Button(master=janela4, text="SIM", command=lambda: janela_config_bd02(banco_selecionado, tabelas_combobox.get(), estrutura_dados_var.get(), somente_estrutura_var.get()))
    sim_button.configure(font=("Helvetica", 18))
    sim_button.grid(row=6, column=0, padx=100, pady=100)

    nao_button = tk.Button(janela4, text="NÃO", command=janela4.destroy)
    nao_button.configure(font=("Helvetica", 18))
    nao_button.grid(row=6, column=2, padx=430, pady=100)

def janela_bd():
    janela3 = tk.Toplevel()
    janela3.title("CFSW MIGRAÇÃO DE DADOS")
    janela3.geometry("900x450")
    janela3.resizable(False, False)

    try:
        cnx = mysql.connector.connect(
            user=db_config["user"],
            password=db_config["password"],
            host=db_config["host"]
        )
        cursor = cnx.cursor()
        cursor.execute("SHOW DATABASES;")
        rows = cursor.fetchall()
        db_options = [row[0] for row in rows]

    except mysql.connector.Error as err:
        print(f"Erro: {err}")
        return

    bancos_combobox = ttk.Combobox(janela3, font=("Helvetica", 12))
    bancos_combobox['values'] = db_options
    bancos_combobox.current(0)
    bancos_combobox.grid(row=3, column=0, padx=10, pady=10)

    label = tk.Label(janela3, text="Selecione um banco de dados", font=("Helvetica", 12))
    label.grid(row=0, column=0, padx=10, pady=10)

    next_button = tk.Button(master=janela3, text="PRÓXIMO", command=lambda: janela_tabela(bancos_combobox.get()))
    next_button.configure(font=("Helvetica", 18))
    next_button.grid(row=6, column=0, padx=100, pady=100)

def janela_config_bd():
    janela2 = tk.Toplevel()
    janela2.title("Configuração do Banco de Dados MySQL")
    janela2.geometry("900x450")

    # Criação dos campos de entrada para conexão ao BD MySQL
    tk.Label(janela2, text="Usuário:").grid(row=0, column=0, padx=10, pady=10)
    username_entry = tk.Entry(janela2, width=20)
    username_entry.grid(row=0, column=1, padx=10, pady=10)

    tk.Label(janela2, text="Senha:").grid(row=1, column=0, padx=10, pady=10)
    password_entry = tk.Entry(janela2, width=20, show="*")
    password_entry.grid(row=1, column=1, padx=10, pady=10)

    tk.Label(janela2, text="Host:").grid(row=2, column=0, padx=10, pady=10)
    host_entry = tk.Entry(janela2, width=20)
    host_entry.grid(row=2, column=1, padx=10, pady=10)

    def salva_config():
        db_config["user"] = username_entry.get()
        db_config["password"] = password_entry.get()
        db_config["host"] = host_entry.get()

        janela2.destroy()
        janela_bd()

    conect_button = tk.Button(master=janela2, text="CONECTAR", command=salva_config)
    conect_button.grid(row=5, column=0, columnspan=2, padx=10, pady=10)

    voltar_button = tk.Button(janela2, text="VOLTAR", command=janela2.destroy)
    voltar_button.grid(row=5, column=2, columnspan=2, padx=10, pady=10)

def main():
    root = tk.Tk()
    root.title("CCFSW MIGRAÇÃO DE DADOS")
    root.geometry("900x450")
    root.resizable(False, False)

    nome = tk.Label(root, text="Bem vindo a ferramenta de migração de dados CFSW", font=("Helvetica", 18))
    nome.grid(row=0, column=0, padx=100, pady=100)

    start_button = tk.Button(master=root, text="INICIAR", command=janela_config_bd)
    start_button.configure(font=("Helvetica", 18))
    start_button.grid(row=6, column=0, padx=100, pady=100)

    quit_button = tk.Button(master=root, text="SAIR", command=root.quit)
    quit_button.configure(font=("Helvetica", 18))
    quit_button.grid(row=6, column=2, padx=430, pady=100)

    root.mainloop()

if __name__ == "__main__":
    main()

Conexão com o banco de dados Oracle bem-sucedida!
Executing: CREATE TABLE "ZONA" ("ZONCODIGO" NUMBER, "ZONNOME" VARCHAR2(15), "ZONCIDCODIGO" NUMBER, PRIMARY KEY ("ZONCODIGO"))
Migração do banco de dados concluída com sucesso!
Conexão com o banco de dados Oracle bem-sucedida!
Executing: CREATE TABLE "BAIRRO" ("BAICODIGO" NUMBER, "BAINOME" VARCHAR2(30), "BAIZONCODIGO" NUMBER, "BAIQTDEPESSOAS" NUMBER, PRIMARY KEY ("BAICODIGO"))
Migração do banco de dados concluída com sucesso!

In [152]:
dsn = cx_Oracle.makedsn('localhost', 1521, service_name='XEPDB1')
conn = cx_Oracle.connect(user="TEST_MIGRACAO", password="123", dsn=dsn)

# Criando um cursor
cursor = conn.cursor()

try:
    # Executando uma consulta SQL
    consulta_sql = "SELECT table_name FROM user_tables"
    cursor.execute(consulta_sql)
    
    # Recuperando os resultados e armazenando em uma lista
    result_oracle = [linha[0] for linha in cursor.fetchall()]
    
finally:
    # Fechando o cursor e a conexão
    cursor.close()
    conn.close()
print(result_oracle)

['CLIENTE', 'BAIRRO', 'ZONA']

In [153]:
 mysql_conn = pymysql.connect(
        user="root",
        password="07114915Sa@",
        host="localhost",
        database="bd2024"
    )
cursor = mysql_conn.cursor()
cursor.callproc("sp_tabela_necessaria", ("bd2024", "cliente"))
tabelas = cursor.fetchall()
print(tabelas)
result_mysql = []
for linha in tabelas:
    result_mysql.append(linha[0])
print(result_mysql)

(('bairro',), ('estadocivil',))
['bairro', 'estadocivil']

In [154]:
verifica(result_oracle,result_mysql )

Já existe a tabela: bairro
Não existe a tabela: estadocivil