In [1]:
import tkinter as tk
from tkinter import messagebox, ttk
import mysql.connector
import cx_Oracle
from tkinter import Menu
import pymysql

db_config = {}
db_configorcl = {}

def filtraTabelasExistentes(lista, lista2):
    lista = [item.upper() for item in lista]
    list_filtrada = []
    for item in lista2:
        if item.upper() in lista:
            print("Já existe a tabela:", item)
        else:
            list_filtrada.append(item)
            print("Não existe a tabela:", item)
    return list_filtrada

def verifica_relacionamento(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura, direcao):
    if direcao == "mysql_to_oracle":
        mysql_conn = pymysql.connect(
            user=db_config["user"],
            password=db_config["password"],
            host=db_config["host"],
            port=int(db_config["port"]),
            database=banco_selecionado
        )
        cursor = mysql_conn.cursor()
        cursor.callproc("sp_tabela_necessaria", (banco_selecionado, tabela_selecionada))
        resultados = cursor.fetchall()
        if resultados:
            for result in resultados:
                migrar_banco_mysql_para_oracle(banco_selecionado, result[0], migrar_estrutura_dados, migrar_somente_estrutura)
            migrar_banco_mysql_para_oracle(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura)
        else:
            migrar_banco_mysql_para_oracle(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura)
    else:
        migrar_banco_oracle_para_mysql(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura)

def migrar_banco_mysql_para_oracle(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura):
    mysql_conn = None
    try:
        dsn = cx_Oracle.makedsn(db_configorcl["host"], db_configorcl["port"], service_name=db_configorcl["service_name"])
        conn = cx_Oracle.connect(user=db_configorcl["user"], password=db_configorcl["password"], dsn=dsn)

        print("Conexão com o banco de dados Oracle bem-sucedida!")

        mysql_conn = mysql.connector.connect(
            user=db_config["user"],
            password=db_config["password"],
            host=db_config["host"],
            port=int(db_config["port"]),
            database=banco_selecionado
        )
        
        mysql_cursor = mysql_conn.cursor()
        mysql_cursor.execute(f"DESCRIBE {tabela_selecionada};")
        columns = mysql_cursor.fetchall()
        
        cursor_oracle = conn.cursor()
        cursor_oracle.execute("SELECT table_name FROM user_tables")
        tabelas_existentes_oracle = [linha[0] for linha in cursor_oracle.fetchall()]

        if tabela_selecionada.upper() in tabelas_existentes_oracle:
            messagebox.showinfo("Tabela Já Existe", f"A tabela '{tabela_selecionada}' já existe no banco de dados Oracle e não será migrada.")
            return

        create_table_sql = f'CREATE TABLE "{tabela_selecionada.upper()}" ('
        pk_columns = []

        for column in columns:
            column_name = column[0]
            column_type = column[1]

            if "int" in column_type.lower():
                oracle_type = "NUMBER"
            elif "varchar" in column_type.lower():
                length = column_type.split('(')[1].split(')')[0]
                oracle_type = f"VARCHAR2({length})"
            elif "char" in column_type.lower():
                length = column_type.split('(')[1].split(')')[0]
                oracle_type = f"CHAR({length})"
            elif "text" in column_type.lower():
                oracle_type = "CLOB"
            elif "datetime" in column_type.lower():
                oracle_type = "DATE"
            else:
                oracle_type = "VARCHAR2(255)"

            create_table_sql += f'"{column_name.upper()}" {oracle_type}, '

        create_table_sql = create_table_sql.rstrip(", ") + ")"
        
        print(f"Executing: {create_table_sql}")
        cursor_oracle.execute(create_table_sql)

        if migrar_estrutura_dados:
            mysql_cursor.execute(f"SELECT * FROM {tabela_selecionada};")
            rows = mysql_cursor.fetchall()
            for row in rows:
                placeholders = ", ".join([":" + str(i + 1) for i in range(len(row))])
                insert_sql = f"INSERT INTO \"{tabela_selecionada.upper()}\" VALUES ({placeholders})"
                cursor_oracle.execute(insert_sql, row)

        conn.commit()

        print("Migração do banco de dados concluída com sucesso!")

    except cx_Oracle.Error as error:
        messagebox.showerror("Erro de Migração", f"Erro ao migrar o banco de dados: {error}")

    finally:
        if mysql_conn is not None:
            mysql_conn.close()
        conn.close()

def migrar_banco_oracle_para_mysql(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura):
    oracle_conn = None
    try:
        dsn = cx_Oracle.makedsn(db_configorcl["host"], db_configorcl["port"], service_name=db_configorcl["service_name"])
        oracle_conn = cx_Oracle.connect(user=db_configorcl["user"], password=db_configorcl["password"], dsn=dsn)

        print("Conexão com o banco de dados Oracle bem-sucedida!")

        mysql_conn = mysql.connector.connect(
            user=db_config["user"],
            password=db_config["password"],
            host=db_config["host"],
            port=int(db_config["port"]),
            database=banco_selecionado
        )
        
        mysql_cursor = mysql_conn.cursor()
        cursor_oracle = oracle_conn.cursor()

        cursor_oracle.execute(f"SELECT column_name, data_type FROM all_tab_columns WHERE table_name = '{tabela_selecionada.upper()}'")
        columns = cursor_oracle.fetchall()
        
        mysql_cursor.execute("Show tables;")
        tabelas_existentes_mysql = [linha[0] for linha in cursor_oracle.fetchall()]

        if tabela_selecionada.upper() in tabelas_existentes_mysql:
            messagebox.showinfo("Tabela Já Existe", f"A tabela '{tabela_selecionada}' já existe no banco de dados MySQL e não será migrada.")
            return

        create_table_sql = f'CREATE TABLE `{tabela_selecionada}` ('

        for column in columns:
            column_name = column[0]
            column_type = column[1]

            if "NUMBER" in column_type.upper():
                mysql_type = "INT"
            elif "VARCHAR2" in column_type.upper():
                mysql_type = "VARCHAR(255)"
            elif "CHAR" in column_type.upper():
                mysql_type = "CHAR(255)"
            elif "CLOB" in column_type.upper():
                mysql_type = "TEXT"
            elif "DATE" in column_type.upper():
                mysql_type = "DATETIME"
            else:
                mysql_type = "VARCHAR(255)"

            create_table_sql += f'`{column_name.lower()}` {mysql_type}, '

        create_table_sql = create_table_sql.rstrip(", ") + ")"
        
        print(f"Executing: {create_table_sql}")
        mysql_cursor.execute(create_table_sql)

        if migrar_estrutura_dados:
            cursor_oracle.execute(f"SELECT * FROM {tabela_selecionada}")
            rows = cursor_oracle.fetchall()
            for row in rows:
                placeholders = ", ".join(["%s" for _ in row])
                insert_sql = f"INSERT INTO `{tabela_selecionada}` VALUES ({placeholders})"
                mysql_cursor.execute(insert_sql, row)

        mysql_conn.commit()

        print("Migração do banco de dados concluída com sucesso!")

    except (cx_Oracle.Error, mysql.connector.Error) as error:
        messagebox.showerror("Erro de Migração", f"Erro ao migrar o banco de dados: {error}")

    finally:
        if oracle_conn is not None:
            oracle_conn.close()
        mysql_conn.close()

def janela_tabela(banco_selecionado, direcao):
    janela4 = tk.Toplevel()
    janela4.title("CFSW MIGRAÇÃO DE DADOS")
    janela4.geometry("900x450")  
    janela4.resizable(False, False)

    try:
        if direcao == "mysql_to_oracle":
            cnx = mysql.connector.connect(
                user=db_config["user"],
                password=db_config["password"],
                host=db_config["host"],
                port=int(db_config["port"]),
                database=banco_selecionado
            )
            cursor = cnx.cursor()
            cursor.execute("SHOW TABLES")
            tabelas = [tabela[0] for tabela in cursor.fetchall()]
            cnx.close()
        else:
            dsn = cx_Oracle.makedsn(db_configorcl["host"], db_configorcl["port"], service_name=db_configorcl["service_name"])
            conn = cx_Oracle.connect(user=db_configorcl["user"], password=db_configorcl["password"], dsn=dsn)
            cursor = conn.cursor()
            cursor.execute("SELECT table_name FROM user_tables")
            tabelas = [linha[0] for linha in cursor.fetchall()]
            conn.close()

        if not tabelas:
            messagebox.showinfo("Sem Tabelas", "Não há tabelas disponíveis para migração.")
            janela4.destroy()
            return
        
        scrollbar = tk.Scrollbar(janela4)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        lista_tabelas = tk.Listbox(janela4, yscrollcommand=scrollbar.set, selectmode=tk.SINGLE)
        lista_tabelas.pack(pady=20, padx=50)

        scrollbar.config(command=lista_tabelas.yview)

        for tabela in tabelas:
            lista_tabelas.insert(tk.END, tabela)

        def migrar_tabela():
            tabela_selecionada = lista_tabelas.get(tk.ACTIVE)
            if not tabela_selecionada:
                messagebox.showwarning("Nenhuma Tabela Selecionada", "Por favor, selecione uma tabela para migrar.")
                return

            migrar_estrutura_dados = messagebox.askyesno("Migrar Estrutura e Dados", "Você deseja migrar a estrutura e os dados da tabela?")
            migrar_somente_estrutura = False

            if not migrar_estrutura_dados:
                migrar_somente_estrutura = messagebox.askyesno("Migrar Apenas Estrutura", "Você deseja migrar apenas a estrutura da tabela?")

            verifica_relacionamento(banco_selecionado, tabela_selecionada, migrar_estrutura_dados, migrar_somente_estrutura, direcao)

        botao_migrar = tk.Button(janela4, text="Migrar Tabela Selecionada", command=migrar_tabela)
        botao_migrar.pack(pady=20)

    except (mysql.connector.Error, cx_Oracle.Error) as error:
        messagebox.showerror("Erro ao Conectar", f"Erro ao conectar com o banco de dados: {error}")
        janela4.destroy()

def conectar():
    banco_selecionado = banco_entry.get()
    direcao = direcao_var.get()
    if not banco_selecionado:
        messagebox.showwarning("Banco Não Selecionado", "Por favor, selecione um banco de dados.")
        return

    janela_tabela(banco_selecionado, direcao)

def sair():
    janela.destroy()

def janela_principal():
    global janela, banco_entry, direcao_var
    janela = tk.Tk()
    janela.title("CFSW MIGRAÇÃO DE DADOS")
    janela.geometry("900x500")
    janela.resizable(False, False)

    # Criação do menu
    barra_menu = Menu(janela)
    menu_arquivo = Menu(barra_menu, tearoff=0)
    menu_arquivo.add_command(label="Sair", command=sair)
    barra_menu.add_cascade(label="Arquivo", menu=menu_arquivo)
    janela.config(menu=barra_menu)

    direcao_var = tk.StringVar()
    direcao_var.set("mysql_to_oracle")

    # Frame para opções de direção
    direcao_frame = tk.Frame(janela)
    direcao_frame.pack(pady=20)

    mysql_to_oracle_radio = tk.Radiobutton(direcao_frame, text="MySQL para Oracle", variable=direcao_var, value="mysql_to_oracle")
    oracle_to_mysql_radio = tk.Radiobutton(direcao_frame, text="Oracle para MySQL", variable=direcao_var, value="oracle_to_mysql")

    mysql_to_oracle_radio.grid(row=0, column=0, padx=20)
    oracle_to_mysql_radio.grid(row=0, column=1, padx=20)

    banco_label = tk.Label(janela, text="Escolha o banco de dados:")
    banco_label.pack()

    banco_entry = ttk.Combobox(janela, width=40)
    banco_entry.pack()

    def carregar_bancos_mysql():
        global db_config
        try:
            mysql_conn = pymysql.connect(
                user=db_config["user"],
                password=db_config["password"],
                host=db_config["host"],
                port=int(db_config["port"]),
            )
            cursor = mysql_conn.cursor()
            cursor.execute("SHOW DATABASES")
            databases = [database[0] for database in cursor.fetchall()]
            banco_entry["values"] = databases
            cursor.close()
            mysql_conn.close()
        except pymysql.Error as error:
            messagebox.showerror("Erro de Conexão", f"Erro ao carregar bancos de dados: {error}")

    def carregar_bancos_oracle():
        global db_configorcl
        try:
            dsn = cx_Oracle.makedsn(db_configorcl["host"], db_configorcl["port"], service_name=db_configorcl["service_name"])
            conn = cx_Oracle.connect(user=db_configorcl["user"], password=db_configorcl["password"], dsn=dsn)
            cursor = conn.cursor()
            cursor.execute("SELECT username FROM all_users")
            users = [user[0] for user in cursor.fetchall()]
            banco_entry["values"] = users
            cursor.close()
            conn.close()
        except cx_Oracle.Error as error:
            messagebox.showerror("Erro de Conexão", f"Erro ao carregar bancos de dados: {error}")

    def definir_banco():
        direcao = direcao_var.get()
        if direcao == "mysql_to_oracle":
            carregar_bancos_mysql()
        else:
            carregar_bancos_oracle()

    definir_banco()

    conectar_btn = tk.Button(janela, text="Conectar", command=conectar)
    conectar_btn.pack(pady=20)

    janela.mainloop()

def login_bancos():
    def conectar_bancos():
        global db_config, db_configorcl
        db_config = {
            "user": mysql_user_entry.get(),
            "password": mysql_pass_entry.get(),
            "host": mysql_host_entry.get(),
            "port": mysql_port_entry.get()
        }
        db_configorcl = {
            "user": oracle_user_entry.get(),
            "password": oracle_pass_entry.get(),
            "host": oracle_host_entry.get(),
            "port": oracle_port_entry.get(),
            "service_name": oracle_serv_entry.get()
        }
        login_window.destroy()
        janela_principal()

    login_window = tk.Tk()
    login_window.title("CFSW MIGRAÇÃO DE DADOS")
    login_window.geometry("600x600")
    login_window.resizable(False, False)

    tk.Label(login_window, text="MySQL Login", font=('Helvetica', 12, 'bold')).pack(pady=10)
    mysql_user_label = tk.Label(login_window, text="Usuário:")
    mysql_user_label.pack()
    mysql_user_entry = tk.Entry(login_window)
    mysql_user_entry.pack()

    mysql_pass_label = tk.Label(login_window, text="Senha:")
    mysql_pass_label.pack()
    mysql_pass_entry = tk.Entry(login_window, show="*")
    mysql_pass_entry.pack()

    mysql_host_label = tk.Label(login_window, text="Host:")
    mysql_host_label.pack()
    mysql_host_entry = tk.Entry(login_window)
    mysql_host_entry.pack()

    mysql_port_label = tk.Label(login_window, text="Porta:")
    mysql_port_label.pack()
    mysql_port_entry = tk.Entry(login_window)
    mysql_port_entry.pack()

    tk.Label(login_window, text="Oracle Login", font=('Helvetica', 12, 'bold')).pack(pady=10)
    oracle_user_label = tk.Label(login_window, text="Usuário:")
    oracle_user_label.pack()
    oracle_user_entry = tk.Entry(login_window)
    oracle_user_entry.pack()

    oracle_pass_label = tk.Label(login_window, text="Senha:")
    oracle_pass_label.pack()
    oracle_pass_entry = tk.Entry(login_window, show="*")
    oracle_pass_entry.pack()

    oracle_host_label = tk.Label(login_window, text="Host:")
    oracle_host_label.pack()
    oracle_host_entry = tk.Entry(login_window)
    oracle_host_entry.pack()

    oracle_port_label = tk.Label(login_window, text="Porta:")
    oracle_port_label.pack()
    oracle_port_entry = tk.Entry(login_window)
    oracle_port_entry.pack()

    oracle_serv_label = tk.Label(login_window, text="Service Name:")
    oracle_serv_label.pack()
    oracle_serv_entry = tk.Entry(login_window)
    oracle_serv_entry.pack()

    connect_btn = tk.Button(login_window, text="Conectar", command=conectar_bancos)
    connect_btn.pack(pady=20)

    login_window.mainloop()

login_bancos()

Conexão com o banco de dados Oracle bem-sucedida!
Executing: CREATE TABLE `CLIENTE` (`clicodigo` INT, `clisexo` CHAR(255), `clirendamensal` INT, `clinome` VARCHAR(255), `clibaicodigo` INT, `clifone` VARCHAR(255), `cliestcodigo` INT, `clidtcadastro` DATETIME, `clidtdesativacao` DATETIME, `clicodigo` INT, `clisexo` CHAR(255), `clirendamensal` VARCHAR(255), `clinome` VARCHAR(255), `clibaicodigo` INT, `clifone` VARCHAR(255), `cliestcodigo` INT, `clidtcadastro` VARCHAR(255), `clidtdesativacao` VARCHAR(255))